spring.application.name=team-task-manager

# Use Railway full DB URL
spring.datasource.url=jdbc:${MYSQL_PUBLIC_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}